#!/bin/sh

. /lib/ralink.sh

# device=sda1
device=`basename $DEVPATH`

#max_usb_name=`block label | tail -1`
#[ -e /dev/sda ] && DISK_NAME="sda"
#[ -e /dev/sdb ] && DISK_NAME="sdb"
#[ -e /dev/sdc ] && DISK_NAME="sdc"
#[ -e /dev/sdd ] && DISK_NAME="sdd"
DISK_NAME=${device:0:3}
logger "diskname $DISK_NAME ******************"
[ $DISK_NAME != "" ] && {
    rm -rf /tmp/file.txt
	cd /dev
	ls $DISK_NAME* | sort -n > /tmp/file.txt
#	sed -i "s/\/dev\/$DISK_NAME//g"   /tmp/file.txt
	max_usb_name=$(tail -1 /tmp/file.txt)
	cd -
}

restart_service()
{
    [ -f /tmp/initdisk ] && rm -rf /tmp/initdisk
    /etc/init.d/appmsh stop &
    
	sleep 2
    
	/etc/waittime.sh open &
    
    if [ -e /dev/sr0 ]; then
		logger "add security disk"
		touch /tmp/security_disk
    fi

    /etc/init.d/xctlsh restart &
    /etc/init.d/lighttpdsh restart &
    /etc/init.d/mpssh restart &
    /etc/init.d/etmsh restart &
	/etc/init.d/dlnash restart &

    /etc/init.d/samba  stop
    /etc/init.d/samba  start

    /etc/init.d/appmsh start &

    /bin/diag.sh &

	mount_ok=`mount | grep  UsbDisk`
	if [ "$mount_ok" != "" ]; then
		echo 0 > /sys/class/leds/timecloud-led-white/brightness
	fi
}


case $(ralink_board_name) in
	timecloud)
		case "$device" in
			sda | sdb | sdc | sdd | md | hd)
				case "$ACTION" in
					add)
						[ -f /tmp/initdisk ] || touch /tmp/initdisk 
						#Tai dian; U Disk
						logger "device=$device; max_usb_name=$max_usb_name"
						[ "$device" = "$max_usb_name" ] && {
							restart_service
						}
					;;
					remove)	
						logger "remove device=$device; max_usb_name=$max_usb_name"
						[ -f /tmp/initdisk ] && rm -rf /tmp/initdisk
						[ -f /tmp/remove_usb ] ||  touch /tmp/remove_usb

						#display status
						echo 0 > /sys/class/leds/timecloud-led-orange/brightness
						
    					/etc/init.d/appmsh		stop
						/etc/init.d/xctlsh  stop
						/etc/init.d/mpssh       stop
						/etc/init.d/lighttpdsh  stop
						/etc/init.d/samba       stop
						/etc/init.d/dlnash      stop

						# stop service pro
						[ -f /tmp/waittime_open ] && rm -rf /tmp/waittime_open

						/etc/waittime.sh close & 
						[ -f /tmp/waittime_close ] && rm -rf /tmp/waittime_close
					
					
						#/bin/umountall /dev/${$device}
						#delete dir
						rm -rf /data/UsbDisk1
						
						if [ -f /tmp/security_disk ]; then
							rm -f /tmp/security_disk
						fi
						/etc/init.d/xctlsh start
						/etc/init.d/mpssh      start
						/etc/init.d/lighttpdsh start
						/etc/init.d/dlnash     start
						/etc/init.d/appmsh     start


					;;
				esac
				;;
			sda* | sdb* | sdc* | sdd* | md* | hd*)
				case "$ACTION" in
				add)
					#display status
					echo 1 > /sys/class/leds/timecloud-led-white-flush/brightness

					[ -f /tmp/quick_umount ] && rm /tmp/quick_umount
					[ -f /tmp/remove_usb ]   && rm /tmp/remove_usb

					logger "device=$device; max_usb_name=$max_usb_name"
					
					# start service pro
					[ "$device" = "$max_usb_name" ] && {
						restart_service
					}
					;;
				esac
				;;
			mmcblk0 | mmcblk1 )
				case "$ACTION" in
					remove)
						#delete dir
						rm -rf /data/UsbDisk2
						
						[ -f /tmp/waittime_sdopen ] && rm -rf /tmp/waittime_sdopen
						/etc/waittime.sh sdclose &
						[ -f /tmp/waittime_sdclose ] && rm -rf /tmp/waittime_sdclose

						status=`mount | grep UsbDisk1`
						if [ "$status" != "" ]; then
							echo 0 > /sys/class/leds/timecloud-led-white/brightness
						else
							echo 0 > /sys/class/leds/timecloud-led-orange/brightness
						fi
				
						/etc/cleansdbackup.sh
						rm -f /tmp/sdinsert
					;;
				esac
				;;
			mmcblk0p*)
				case "$ACTION" in
				add)
					#status=`mount | grep UsbDisk1`
					#if [ "$status" != "" ]; then
						#display status
						#backup  data
						#echo 1 > /sys/class/leds/timecloud-led-white-flush/brightness
						
						# start service pro
						/etc/waittime.sh sdopen &
					
						/etc/autosdbackup.sh
						touch /tmp/sdinsert
					#else
						echo 0 > /sys/class/leds/timecloud-led-orange/brightness
						status=`mount | grep UsbDisk1`
                        if [ "$status" != "" ]; then
							sleep 1
                            echo 0 > /sys/class/leds/timecloud-led-white/brightness
						fi
					#fi
					/bin/diag.sh &
					;;
				esac
				;;
			esac
			;;
esac

