#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2012 OpenWrt.org

START=80
SMB_FILE=/tmp/smbswitch

mk_smb_conf_link() {
	#arg conf file-name e.g. smb.conf
	local etc_conf=/etc/samba/$1
	local var_conf=/var/etc/$1
	
	if [ ! -f "${etc_conf}" -o "`readlink ${etc_conf}`" != "${var_conf}" ]; then
		echo "make symbolic link ${etc_conf} --> ${var_conf}"
		rm -f ${etc_conf}
		rm -f ${var_conf}
		touch ${var_conf}
		ln -s ${var_conf} ${etc_conf}
		sync
	fi
}

start() {
	mkdir -p /etc/samba
	mkdir -p /var/etc

	rm -rf ${SMB_FILE}
	/bin/resetboot -l
	if [ ! -f ${SMB_FILE} ]; then
		SMB_SW="1"
	else
		SMB_SW=`cat ${SMB_FILE}`
	fi

	/bin/resetboot -r
	if [ "${SMB_SW}" != "0" ]; then
		mk_smb_conf_link "smb.conf"
		mk_smb_conf_link "smbpasswd"

		/bin/smbconfig
		/etc/init.d/smbmod
		service_start /usr/sbin/smbd -D
		service_start /usr/sbin/nmbd -D
	
		system=$(awk 'BEGIN{FS="[ \t]+:[ \t]"} /system type/ {print $2}' /proc/cpuinfo)
	
		[  "$system" ==  "MediaTek MT7621"  ] &&  {
			#粗粮 trash can fucked
			echo 3 > /proc/irq/3/smp_affinity  #GMAC
			echo 3 > /proc/irq/4/smp_affinity  #PCIe0
			echo 3 > /proc/irq/24/smp_affinity #PCIe1
			echo 3 > /proc/irq/25/smp_affinity #PCIe2
			echo 3 > /proc/irq/19/smp_affinity #VPN
			echo 3 > /proc/irq/20/smp_affinity #SDXC
			echo 3 > /proc/irq/22/smp_affinity #USB
		}
		[  "$system" ==  "Realtek RTL8198CS"  ] &&  {
			#粗粮 trash can2 will be fucked
			echo 1 > /proc/irq/3/smp_affinity  #GMAC
		}
		#PandoraBox Samba for SMP Enable
		pbmsa-utils 1
	fi
}

stop() {
	service_stop /usr/sbin/smbd
	service_stop /usr/sbin/nmbd
}
