#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2015 time.xunlei.com

START=98

PROG=/bin/xctl
PID_FILE=/var/run/xctl.pid

start()
{
	${PROG}
}

stop()
{
	killall -9 xctl
	rm -f ${PID_FILE}
}

restart()
{
	stop
	sleep 2
	start
}
